### ISSUE TITLE
setupv2.sh bug: misleading cln.service message

### ISSUE THREAD

**Issue by kobiebotha** [blckbx/tunnelsats#41]
My setup:

- Bare metal CLN
- CLN Service configured as `/etc/systemd/system/cln.service`

Steps to reproduce:

- Run `sudo bash setupv2.sh`
- Select option 4 (Bare Metal)
- Enter "CLN"

Result: 

The below message is printed

```
Looking for systemd service...
> /etc/systemd/system/lightningd.service / /etc/systemd/system/cln.service not found. Setup aborted.
```

However, as you can see [on line 139](https://github.com/blckbx/tunnelsats/blob/main/scripts/setupv2.sh#L139) of `setupv2.sh`, it's only checking for `/etc/systemd/system/lightningd.service` <-- doesn't check for `cln.service` as per the error message printed on stdout

**Comment by blckbx** [comment]
Hello @kobiebotha,
yes, you're right and thanks for reporting! 

Older version of RaspiBolt's CLN guide created a systemd service called `cln.service`. This has been changed recently to comply to standard naming convention of core-lightning. The service has been renamed to `lightningd.service`. 

A cleanup of the scripts is in the making, now that RaspiBolt merged the naming branch.
